### ISSUE TITLE
tls - invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by sreedhar26** [Azure/application-gateway-kubernetes-ingress#629] opened 2019-10-25 15:53 UTC
Without tls secret in AKS, if I deploy AGIC the deployment is successful and I can see Rules, Listeners, Http Settings, Backend pools created fine.   The listeners were created with HTTP.   I would like to apply ssl for listeners and created secret and updated ingress yaml with secret name, re-applied updated ingress and when I check AGIC pod I see following error....

I1025 15:31:36.413666       1 redirects.go:54] [brownfield] Existing Redirects AGIC will remove: n/a
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x12bfe7d]

goroutine 49 [running]:
github.com/Azure/application-gateway-kubernetes-ingress/pkg/appgw.(*appGwConfigBuilder).groupListenersByListenerIdentifier(0xc00099e240, 0xc0006c8900, 0xc0008211f8)
        /home/vsts/work/1/s/gopath/src/github.com/Azure/application-gateway-kubernetes-ingress/pkg/appgw/frontend_listeners.go:190 +0x32d
github.com/Azure/application-gateway-kubernetes-ingress/pkg/appgw.(*appGwConfigBuilder).getRules(0xc00099e240, 0xc0006c8900, 0x0, 0x0, 0xc000636780, 0x3, 0x4, 0xc0007bdcc0)
        /home/vsts/work/1/s/gopath/src/github.com/Azure/application-gateway-kubernetes-ingress/pkg/appgw/requestroutingrules.go:67 +0x6c
github.com/Azure/application-gateway-kubernetes-ingress/pkg/appgw.(*appGwConfigBuilder).RequestRoutingRules(0xc00099e240, 0xc0006c8900, 0x0, 0x0)
        /home/vsts/work/1/s/gopath/src/github.com/Azure/application-gateway-kubernetes-ingress/pkg/appgw/requestroutingrules.go:24 +0x8a
github.com/Azure/application-gateway-kubernetes-ingress/pkg/appgw.(*appGwConfigBuilder).Build(0xc00099e240, 0xc0006c8900, 0x0, 0x0, 0x15)
        /home/vsts/work/1/s/gopath/src/github.com/Azure/application-gateway-kubernetes-ingress/pkg/appgw/configbuilder.go:108 +0x384
github.com/Azure/application-gateway-kubernetes-ingress/pkg/controller.AppGwIngressController.MutateAppGateway(0x184a800, 0xc0001dc000, 0xc000042056, 0x24, 0xc000046055, 0x7, 0xc00004400b, 0x17, 0xc000273530, 0xc000347f00, ...)
        /home/vsts/work/1/s/gopath/src/github.com/Azure/application-gateway-kubernetes-ingress/pkg/controller/mutate_app_gateway.go:125 +0xa2b
github.com/Azure/application-gateway-kubernetes-ingress/pkg/worker.(*Worker).Run(0xc0002539a0, 0xc000337e60, 0xc00009e2a0)
        /home/vsts/work/1/s/gopath/src/github.com/Azure/application-gateway-kubernetes-ingress/pkg/worker/worker.go:52 +0x34e
created by github.com/Azure/application-gateway-kubernetes-ingress/pkg/controller.(*AppGwIngressController).Start
        /home/vsts/work/1/s/gopath/src/github.com/Azure/application-gateway-kubernetes-ingress/pkg/controller/controller.go:72 +0x1b5

AGIC deployed in default namespace, watching all namespaces
Ingress.yaml deployed in a separate namespace
AGIC version - 0.10.0-rc4
Application gateway - Standard V2

I don't think I have seen this issue with 0.9.0 version of AGIC.

**Comment by draychev** [comment] 2019-10-25 16:32
@sreedhar26 thanks for the detailed description and stack trace.  Could you share your `AzureIngressProhibitedTarget` and `Ingress` resources?

**Comment by sreedhar26** [comment] 2019-10-25 16:43
Ingress.yaml - 

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: bluegreeningress
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/ssl-redirect: "true"
    
spec:
  tls:
    - hosts:
      - contoso.com
      - stage.contoso.com
      secretName: prod-secret-wildcard
  rules:
  - host: contoso.com
    http: 
      paths:
      - path: /graphiql
        backend:
          serviceName: graphql-primary
          servicePort: 5000
      - path: /
        backend:
          serviceName: frontend-primary
          servicePort: 80
  - host: stage.contoso.com
    http:
      paths:
      - path: /graphiql
        backend:
          serviceName: graphql-stage
          servicePort: 5000
     - path: /
        backend:
          serviceName: frontend-stage
          servicePort: 80
        
I have removed prohibit-all-targets and I have only one left which is below
AzureIngressProhibiteTarget - 

apiVersion: "appgw.ingress.k8s.io/v1"
kind: AzureIngressProhibitedTarget
metadata:
  name: identity-contoso-com
spec:
  hostname: identity.contoso.com

**Comment by draychev** [comment] 2019-10-26 07:02
@sreedhar26 we have a fix for the root cause of this https://github.com/Azure/application-gateway-kubernetes-ingress/pull/630
As soon as we are confident in the fix, it will be merged and will let you know of a new version so you can install it - early next week!
Thanks for helping us troubleshoot this.

**Comment by evmimagina** [comment] 2019-10-26 17:30
Hi,

I'm think I'm affected by the same bug. How can I install it once it's available?

thanks,

**Comment by draychev** [comment] 2019-10-29 01:45
@evmimagina thanks for reporting this issue - it seems like something slightly different than the original issue reported.  I'll take a look at the stack trace you provided.

**Comment by draychev** [comment] 2019-10-29 01:47
@sreedhar26 We just published a new release - https://github.com/Azure/application-gateway-kubernetes-ingress/releases/tag/0.10.0-rc5 which addresses the issue you ran into.

Would you be so kind to `helm repo update` and upgrade to `0.10.0-rc5` ?
Detailed instructions on how to upgrade are [here](https://github.com/Azure/application-gateway-kubernetes-ingress/blob/e28a1388ddc0cc0fa8efbedc595ae43ac7c91be2/docs/how-tos/helm-upgrade.md#upgrade)

**Comment by draychev** [comment] 2019-10-29 01:58
@evmimagina You have ran into an interesting edge case it seems - could you please open a new issue (so we can keep track of what you observed separately).

Would you be able to share with the following:
1) what version of the AGIC you are using (`helm list` would tell us this)
2) would you be able to provide a sanitized versions of your Ingress and Service kubernetes resources?

It looks like we are running into a situation where we are making unsafe assumptions about a pod or a service struct existing, but it is hard to tell without the context above. Thanks!

**Comment by sreedhar26** [comment] 2019-10-29 02:38
@draychev Thank you so much for the quick turnaround.  I just installed 0.10.0-rc5 and the issue is fixed.   Please close this ticket.

Update instructions - 

- helm repo update

- Detailed instructions on how to upgrade are [here](https://github.com/Azure/application-gateway-kubernetes-ingress/blob/e28a1388ddc0cc0fa8efbedc595ae43ac7c91be2/docs/how-tos/helm-upgrade.md#upgrade)

In case if you have any prohibited targets you need to follow below instructions - 

- kubectl get AzureIngressProhibitedTargets

- kubectl delete AzureIngressProhibitedTarget prohibit-all-targets

- delete ingress resource and re-create it again, kubectl apply -f <ingress.yaml file location>

**Closed** 2019-10-29 17:32 UTC
