### ISSUE TITLE
Validation error: unable to recognize "": no matches for kind "AzureIdentity" in version "aadpodidentity.k8s.io/v1"

### ISSUE THREAD

**Issue by rnkhouse** [Azure/application-gateway-kubernetes-ingress#116] opened 2019-03-18 18:24 UTC
**Describe the bug**
I am following brownfield deployment guide to setup application gateway. Using the helm-config.yaml template and getting below error:

>Error: validation failed: [unable to recognize "": no matches for kind "AzureIdentity" in version "aadpodidentity.k8s.io/v1", unable to recognize "": no matches for kind "AzureIdentityBinding" in version "aadpodidentity.k8s.io/v1"]

**To Reproduce**
Use existing kubernetes cluster, add application gateway in a different resource group and follow the brownfield deployment guide.

**Comment by paviad** [comment] 2019-07-27 11:06
I have this problem as well, how did you resolve this?

**Comment by delqn** [comment] 2019-07-29 17:29
I'm also interested in learning more about **when** this error occurs and **how** @rnkhouse resolved it.

@paviad: We have seen this error in a few scenarios. This could be a race condition when Helm attempts to create an instance of the `AzureIdentity` CRD, before the CRD itself is ready. It could also be related to a syntax error in the helm YAML files.

@paviad To isolate the race condition - do you have the following CRDs when you `kubectl get crds` ?
  - `azureassignedidentities.aadpodidentity.k8s.io`
  - `azureidentities.aadpodidentity.k8s.io`
  - `azureidentitybindings.aadpodidentity.k8s.io`

If you don't have these CRDs - you can install them with:
  - For a non-RBAC AKS cluster: `kubectl create -f https://raw.githubusercontent.com/Azure/aad-pod-identity/master/deploy/infra/deployment.yaml`
  - For RBAC: `kubectl create -f https://raw.githubusercontent.com/Azure/aad-pod-identity/master/deploy/infra/deployment-rbac.yaml`

**Comment by rajarshi-singh** [comment] 2019-09-15 18:46
I am having the same issue on Win containers within Azure Kubernetes Service.

**Comment by snapfisher** [comment] 2020-02-19 23:11
I am having the same issue trying to deploy the greenfield deployment from Azure DevOps.  I could not fix this issue the remote helm charts and the helm repo, so I downloaded all of the helm charts into my project directly, and I still have the issue.  I am using two different pipelines, one to deploy the arm templates and one to do the helm deployment to the cluster.  I can get it to deploy using the manual steps.

**Comment by akshaysngupta** [comment] 2020-02-23 20:27
Are you using [CD document](https://github.com/Azure/application-gateway-kubernetes-ingress/blob/master/docs/how-tos/continuous-deployment.md) to setup the pipeline ?

**Comment by snapfisher** [comment] 2020-02-23 20:42
No.  I was not aware that that existed.  I had the manual procedures and thought I should not need any major modifications from that.

I'll go through the procedure this week.  See if I can get it to run, and note where there are any discrepancies.  Maybe they will be appropriate for the documentation page.

Thx.


On Feb 23, 2020 3:27 PM, Akshay Gupta <notifications@github.com> wrote:

Are you using CD document<https://github.com/Azure/application-gateway-kubernetes-ingress/blob/master/docs/how-tos/continuous-deployment.md> to setup the pipeline ?

**Comment by no3am** [comment] 2020-02-25 17:23
I'm not sure if I should keep following this thread or open a new one as I'm seeing something similar - please advise.

My setup:
create an AKS
Create an appgw
trying to follow the brownfield deployment document, I reached the install part:
`helm install agic ./azure_agic/ingress-azure/ --namespace demo
`
Error:
`Error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "Deployment" in version "apps/v1beta2"`
to my understanding I should just change the api version, but I'm still hesitating as I cloned the repo as is and just changed the values file, so it should work out of the box?
using aad pod identity.
using helm3

**Comment by no3am** [comment] 2020-02-25 21:04
I'm not sure if I should keep following this thread or open a new one as I'm seeing something similar - please advise.

My setup:
create an AKS
Create an appgw
trying to follow the brownfield deployment document, I reached the install part:
`helm install agic ./azure_agic/ingress-azure/ --namespace demo
`
Error:
`Error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "Deployment" in version "apps/v1beta2"`
to my understanding I should just change the api version, but I'm still hesitating as I cloned the repo as is and just changed the values file, so it should work out of the box?
using aad pod identity.
using helm3

**Comment by akshaysngupta** [comment] 2020-02-25 22:25
@no3am [This PR ](https://github.com/Azure/application-gateway-kubernetes-ingress/pull/713)is addressing the issue mentioned.

**Comment by snapfisher** [comment] 2020-02-27 22:42
That pipeline does not install AGIC.  It pushes some kind of AGIC configuration to the cluster, but no AGIC is installed in Azure.

It’s really killing me that transferring the steps from https://docs.microsoft.com/en-us/azure/application-gateway/ingress-controller-install-new does not produce a working configuration.  My last attempts all end in “bad gateway”.  I am assuming that it is something in the ARM template, which requires me to be logged in as me, and not as the ADO service connection, but which is failing silently.

I am going to see if I can fix your version, as I see there is CLI instructions for installing AGIC available.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by Yiyito11** [comment] 2020-04-17 13:29
If I create a new helm chart using HELM from official documentation I can create the ingress controller, but If I want to update it with following command:  `helm upgrade -f helm-demo-eastus.yml tan-ladybug application-gateway-kubernetes-ingress/ingress-azure  --recreate-pods`

I´m getting the issue is mentioned in the post. How can I fix this?

**Comment by akshaysngupta** [comment] 2020-05-19 22:47
@Yiyito11 This was happening due to a breaking change in the AAD Pod Identity project.
We have addressed the issue in 1.2.0-rc2. Please let us know if you see the issue after upgrading.

**Closed** 2020-05-19 22:51 UTC

**Comment by AlexanderViken** [comment] 2020-06-12 08:45
I am facing the same issue on a new greenfield AKS cluster (1.16.9) now I have validated aadpodidentity and managed identity configuration and as far as I can tell it is working. Helm 3.2.0.  What is it looking for where when it is unable to recognize ""?

command:
helm install --debug --wait --set verbosityLevel=5 --set appgw.subscriptionId=*** --set appgw.resourceGroup=rg-networking-***-dev --set appgw.name=appgw-***-dev --set appgw.usePrivateIP=false --set appgw.shared=false --set armAuth.type=aadPodIdentity --set armAuth.identityResourceID=/subscriptions/***/resourcegroups/rg-networking-***-dev/providers/Microsoft.ManagedIdentity/userAssignedIdentities/appgw-ident-***-dev --set armAuth.identityClientID=*** --set rbac.enabled=true agic-deploy application-gateway-kubernetes-ingress/ingress-azure


-----output---------------
install.go:159: [debug] Original chart version: ""
install.go:176: [debug] CHART PATH: C:\Users\***\AppData\Local\Temp\helm\repository\ingress-azure-1.0.0.tgz

Error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "Deployment" in version "apps/v1beta2"
helm.go:84: [debug] unable to recognize "": no matches for kind "Deployment" in version "apps/v1beta2"
unable to build kubernetes objects from release manifest
helm.sh/helm/v3/pkg/action.(*Install).Run
        /home/circleci/helm.sh/helm/pkg/action/install.go:252
main.runInstall
        /home/circleci/helm.sh/helm/cmd/helm/install.go:229
main.newInstallCmd.func1
        /home/circleci/helm.sh/helm/cmd/helm/install.go:117
github.com/spf13/cobra.(*Command).execute
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842
github.com/spf13/cobra.(*Command).ExecuteC
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950
github.com/spf13/cobra.(*Command).Execute
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.main
        /home/circleci/helm.sh/helm/cmd/helm/helm.go:83
runtime.main
        /usr/local/go/src/runtime/proc.go:203
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1357

**Comment by AlexanderViken** [comment] 2020-06-12 09:12
And I am getting a similar issue running helm upgrade on another cluster from azure devops pipelines. The pipeline worked fine first time, second time if fails.

[command]C:\hostedtoolcache\windows\helm\3.1.1\x64\windows-amd64\helm.exe upgrade --install --wait --set verbosityLevel=3 --set appgw.subscriptionId=xxx --set appgw.resourceGroup=rg-networking-xxx-prod --set appgw.name=appgw-xxx-prod --set appgw.usePrivateIP=false --set appgw.shared=false --set armAuth.type=aadPodIdentity --set armAuth.identityResourceID=/subscriptions/xxx/resourcegroups/rg-networking-xxx-prod/providers/Microsoft.ManagedIdentity/userAssignedIdentities/appgw-ident-xxx-prod --set armAuth.identityClientID=xxx --set rbac.enabled=true --debug agic-deploy application-gateway-kubernetes-ingress/ingress-azure

history.go:52: [debug] getting history for release agic-deploy
upgrade.go:82: [debug] preparing upgrade for agic-deploy
Error: UPGRADE FAILED: unable to recognize "": no matches for kind "Deployment" in version "apps/v1beta2"
helm.go:75: [debug] unable to recognize "": no matches for kind "Deployment" in version "apps/v1beta2"
UPGRADE FAILED
##[error]history.go:52: [debug] getting history for release agic-deploy
upgrade.go:82: [debug] preparing upgrade for agic-deploy
Error: UPGRADE FAILED: unable to recognize "": no matches for kind "Deployment" in version "apps/v1beta2"
helm.go:75: [debug] unable to recognize "": no matches for kind "Deployment" in version "apps/v1beta2"

UPGRADE FAILED
main.newUpgradeCmd.func1
	/home/circleci/helm.sh/helm/cmd/helm/upgrade.go:138
github.com/spf13/cobra.(*Command).execute
	/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826
github.com/spf13/cobra.(*Command).ExecuteC
	/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914
github.com/spf13/cobra.(*Command).Execute
	/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
main.main
	/home/circleci/helm.sh/helm/cmd/helm/helm.go:74
runtime.main
	/usr/local/go/src/runtime/proc.go:203
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1357

**Comment by akshaysngupta** [comment] 2020-06-12 15:59
@AlexanderViken Please add `--version 1.2.0-rc3`.
When using a newer k8s version >= `1.16`, AGIC version <= `1.0.0` breaks as the deployment api version `apps/v1beta2` is deprecated.

https://github.com/Azure/application-gateway-kubernetes-ingress/blob/master/CHANGELOG/CHANGELOG-1.2.md#features

**Comment by AlexanderViken** [comment] 2020-06-15 07:02
Thank you!
