### ISSUE TITLE
Backend health always unhealthy on windows nodes

### ISSUE THREAD

**Issue by WolterKamphuis** [Azure/application-gateway-kubernetes-ingress#535] opened 2019-09-15 16:38 UTC
**Describe the bug**
For a client 'm testing a hybrid Linux/Windows AKS cluster with the AGIC. It works fine for Linux containers but I can't seem to get Windows containers online with the AGW.

I'm using AGIC 0.9.0-rc2 with AKS 1.15.3. I've modified the example ARM deploy to include a Windows nodepool.

I've created a test setup with two identical containers, one Linux and one Windows container. They both work fine when using the default Nginx ingress controller. However the windows containers always register as unhealthy on the AGW.

dotnet-test is the Windows container (just the dotnet/asp sample from MS).

The backend pool:
<img width="977" alt="Screenshot 2019-09-15 at 18 17 48" src="https://user-images.githubusercontent.com/37590214/64924473-2af9b000-d7e5-11e9-8ae6-ba70e46ae3f9.png">

HTTP settings:
<img width="977" alt="Screenshot 2019-09-15 at 18 18 22" src="https://user-images.githubusercontent.com/37590214/64924480-3a78f900-d7e5-11e9-80c9-95e2a7945033.png">

Listeners:
<img width="977" alt="Screenshot 2019-09-15 at 18 18 57" src="https://user-images.githubusercontent.com/37590214/64924492-4d8bc900-d7e5-11e9-8a44-42dd55cd7b7a.png">

Health probes:
<img width="977" alt="Screenshot 2019-09-15 at 18 19 55" src="https://user-images.githubusercontent.com/37590214/64924503-74e29600-d7e5-11e9-89c5-81da6b8c20dd.png">

Backend health:
<img width="977" alt="Screenshot 2019-09-15 at 18 17 03" src="https://user-images.githubusercontent.com/37590214/64924467-0e5d7800-d7e5-11e9-80f9-e37655d8f2c6.png">

**To Reproduce**
I've created a test setup with two identical containers, one Linux and one Windows container. The ARM template for the hybrid cluster is here: [aks-agw-windows-template.json](https://github.com/WolterKamphuis/aks-agw-windows-demo/blob/master/aks-agw-windows-template.json)

This is the Windows container deployment with ingress [deploy-dotnet-test-agw.yaml](https://github.com/WolterKamphuis/aks-agw-windows-demo/blob/master/deploy-dotnet-test-agw.yaml)

**Ingress Controller details**
* Output of `kubectl describe pod <ingress controller`> . The <ingress controller> pod name can be obtained by running `helm list`. 
```
➜ kubectl describe pod/application-gateway-ingress-azure-f568f78b5-z5w59 
Name:               application-gateway-ingress-azure-f568f78b5-z5w59
Namespace:          default
Priority:           0
PriorityClassName:  <none>
Node:               aks-agentpool-35064155-vmss000000/10.0.0.35
Start Time:         Sun, 15 Sep 2019 16:42:44 +0200
Labels:             app=ingress-azure
                    pod-template-hash=f568f78b5
                    release=application-gateway
Annotations:        <none>
Status:             Running
IP:                 10.0.0.42
Controlled By:      ReplicaSet/application-gateway-ingress-azure-f568f78b5
Containers:
  ingress-azure:
    Container ID:   docker://3f73876bed0e2438dddf42f54d338daa122e9a37410b8ae97643126a8ac309fa
    Image:          mcr.microsoft.com/azure-application-gateway/kubernetes-ingress:0.9.0-rc2
    Image ID:       docker-pullable://mcr.microsoft.com/azure-application-gateway/kubernetes-ingress@sha256:d9eb24e50bf36f51bfebb056a1af2a6954efc347528ea4ecdf72a21a037ada24
    Port:           <none>
    Host Port:      <none>
    State:          Running
      Started:      Sun, 15 Sep 2019 16:42:56 +0200
    Ready:          True
    Restart Count:  0
    Liveness:       http-get http://:8123/health/alive delay=15s timeout=1s period=20s #success=1 #failure=3
    Readiness:      http-get http://:8123/health/ready delay=5s timeout=1s period=10s #success=1 #failure=3
    Environment Variables from:
      application-gateway-cm-ingress-azure  ConfigMap  Optional: false
    Environment:
      AZURE_AUTH_LOCATION:  /etc/Azure/Networking-AppGW/auth/armAuth.json
    Mounts:
      /etc/Azure/Networking-AppGW/auth from networking-appgw-k8s-azure-service-principal-mount (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from application-gateway-sa-ingress-azure-token-9l7rk (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             True 
  ContainersReady   True 
  PodScheduled      True 
Volumes:
  networking-appgw-k8s-azure-service-principal-mount:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  networking-appgw-k8s-azure-service-principal
    Optional:    false
  application-gateway-sa-ingress-azure-token-9l7rk:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  application-gateway-sa-ingress-azure-token-9l7rk
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  beta.kubernetes.io/os=linux
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:          <none>
```

* Output of `kubectl logs <ingress controller>. 

```
➜ kubectl logs pod/application-gateway-ingress-azure-f568f78b5-z5w59  
ERROR: logging before flag.Parse: I0915 14:42:56.527647       1 main.go:294] Using verbosity level 3 from environment variable APPGW_VERBOSITY_LEVEL
I0915 14:42:56.527759       1 main.go:195] Creating authorizer from file referenced by AZURE_AUTH_LOCATION environment variable: /etc/Azure/Networking-AppGW/auth/armAuth.json
I0915 14:42:56.801257       1 main.go:117] Ingress Controller will observe all namespaces.
I0915 14:42:56.840257       1 context.go:122] k8s context run started
I0915 14:42:56.840875       1 context.go:161] Waiting for initial cache sync
I0915 14:42:56.942329       1 context.go:169] Initial cache sync done
I0915 14:42:56.942350       1 context.go:170] k8s context run finished
I0915 14:42:56.942477       1 worker.go:33] Worker started
I0915 14:42:56.942522       1 main.go:140] Starting Health Probe Server on :8123
E0915 14:42:57.123586       1 process.go:87] no Ingress in the pruned Ingress list. Please check Ingress events to get more information
I0915 14:48:25.755266       1 process.go:133] BEGIN AppGateway deployment
I0915 14:48:46.285050       1 process.go:156] Applied App Gateway config in 20.529736529s
I0915 14:48:46.285080       1 process.go:165] cache: Updated with latest applied config.
I0915 14:48:46.285557       1 process.go:171] END AppGateway deployment
I0915 14:48:46.346205       1 process.go:133] BEGIN AppGateway deployment
I0915 14:49:06.673887       1 process.go:156] Applied App Gateway config in 20.327644897s
I0915 14:49:06.673920       1 process.go:165] cache: Updated with latest applied config.
I0915 14:49:06.674498       1 process.go:171] END AppGateway deployment
etc ...
```

* Any Azure support tickets associated with this issue.

**Comment by WolterKamphuis** [comment] 2019-09-18 07:32
Is there anybody who's using the AGIC successfully with Windows nodes ? If so what version of AKS and the AGIC are you using ?

**Comment by akshaysngupta** [comment] 2019-09-18 18:21
Thanks for reporting! We are going to try reproduce this.

**Comment by vavane-ms** [comment] 2019-09-20 18:12
Are there any news on this?

**Comment by akshaysngupta** [comment] 2019-09-23 18:25
@WolterKamphuis @vavane-ms Thanks for the patience.
I was also able to reproduce this. Moreover, I confirmed that AppGW is failing to create a TCP connection to Pod on the Windows VM. I am working with the AKS team and will be back with updates soon.

**Comment by PatrickLang** [comment] 2019-10-01 20:34
So the problem here is that the cni.conf is being created with two different outbound NAT exception rules for the same address but different suffix lengths. The second exception isn't applied.

From what I gather, these correspond to the POD CIDR range (10.0.0.0/16) for the cluster, and the VNET range (10.0.0.0/8). All of these are routable by the Azure VNET so no outbound NAT is required from the pods.

```
{
    "cniVersion":  "0.3.0",
    "name":  "azure",
    "plugins":  [
                    {
                        "type":  "azure-vnet",
                        "mode":  "bridge",
                        "bridge":  "azure0",
                        "capabilities":  {
                                             "portMappings":  true,
                                             "dns":  true
                                         },
                        "ipam":  {
                                     "type":  "azure-vnet-ipam"
                                 },
                        "dns":  {
                                    "Nameservers":  [
                                                        "10.2.0.10",
                                                        "168.63.129.16"
                                                    ],
                                    "Search":  [
                                                   "svc.cluster.local"
                                               ]
                                },
                        "AdditionalArgs":  [
                                               {
                                                   "Name":  "EndpointPolicy",
                                                   "Value":  {
                                                                 "Type":  "OutBoundNAT",
                                                                 "ExceptionList":  [
                                                                                       "10.0.0.0/16",
                                                                                       "10.240.0.0/16",
                                                                                       "10.0.0.0/8"
                                                                                   ]
                                                             }
                                               },
                                               {
                                                   "Name":  "EndpointPolicy",
                                                   "Value":  {
                                                                 "Type":  "ROUTE",
                                                                 "DestinationPrefix":  "10.2.0.0/16",
                                                                 "NeedEncap":  true
                                                             }
                                               }
                                           ]
                    }
                ]
}
```

**Comment by qmalexander** [comment] 2020-01-22 22:05
Any updates on this?

**Comment by vavane-ms** [comment] 2020-01-22 22:12
I believe this is fixed; you should be able to verify with the latest stable release.

**Comment by qmalexander** [comment] 2020-01-23 07:59
> I believe this is fixed; you should be able to verify with the latest stable release in all Azure regions (the problem was not in the ingress controller).

Hi @vavane-ms we use aksEngineVersion: v0.45.0-1 aks for our windows nodes. So is there a later version?

**Comment by vavane-ms** [comment] 2020-01-23 18:20
It should be fixed there. It seems you are hitting a different problem in the AKS engine with the same symptoms.

**Comment by qmalexander** [comment] 2020-01-23 18:39
@vavane-ms aha ok. Do you think I should supply a new issue or do a support ticket? I did a comment in  #1367 as well. There I confirm that the ag get the correct IP to the pod.

**Comment by akshaysngupta** [comment] 2020-02-28 20:05
This is now fixed.
Please give this document a try to setup a AGIC with windows nodes:
https://github.com/Azure/application-gateway-kubernetes-ingress/blob/master/docs/setup/install-new-windows-cluster.md

**Closed by akshaysngupta** 2020-02-28 20:05 UTC

**Comment by andresm53** [comment] 2020-07-14 15:59
Hi @akshaysngupta 
I followed https://azure.github.io/application-gateway-kubernetes-ingress/setup/install-new-windows-cluster/ but instead of using the default VNET/subnets, I used these ranges:

        "aksSubnetAddressPrefix": {
            "defaultValue": "192.168.0.0/24",
            "type": "string",
            "metadata": {
                "description": "Containers DNS server IP address."
            }
        },
        "applicationGatewaySubnetAddressPrefix": {
            "defaultValue": "192.168.1.0/24",
            "type": "string",
            "metadata": {
                "description": "Containers DNS server IP address."
            }
        }

and instead of using the default Kubernetes version, I used this one (because the default one wasn't available):

        "kubernetesVersion": {
            "defaultValue": "1.17.7",
            "type": "string",
            "metadata": {
                "description": "The version of Kubernetes."
            }
        }

And I ended up getting the same error describes in this issue. Application Gateway backend health shows "Time taken by the backend ..."

Do you know if there is an additional config that needs to be done, in order to make this work?

As a workaround, I found that changing the Application Gateway subnet to 10.x.x.x (I used 10.1.0.0/16) fixes the issue. 

Thanks.

**Comment by pwelp** [comment] 2020-09-20 19:27
Was the root cause ever determined? 

I have a setup where the AKS cluster is using the 11.1.0.0/22 subnet, application gateway is using the 11.1.4.0/22.

However for all my windows pods, I see that "Time taken by the backend to respond to application gateway's health probe is more than the time-out threshold in the probe configuration. Either increase the time-out threshold in the probe configuration or resolve the backend issues. To learn more visit - https://aka.ms/ProbeTimeOut"

is the problem that the application gateway **HAS** to use the subnet 10.1.0.0/16? 
 
@akshaysngupta if that is the required subnet, that would probably a good thing to document?

**Comment by andresm53** [comment] 2020-09-21 14:55
Hi @pwelp 

Back on July I ended up opening a support case on what I reported above. Back then, the support engineer concluded that "The Engineering team was engaged and confirmed that this was a known issue. Appears that they identified this as a regression issue which was fixed per https://github.com/Azure/aks-engine/pull/2725  - but the fix  didn’t make  it in time for some recent AKS release branch. The Engineering Team later  confirmed that the fix has recently  been merged to into a master branch  after some testing over several days. So if everything else goes according to plan, it should soon be deployed but they provided a wide window of 8/3 – 8/28."

I haven't tested this again myself, so I can't confirm if it was already fixed or not.

By the way, quick comment just in case: you mentioned above you are using 11.x.x.x, which is a bit weird, because that is not a private address space (10.x.x.x, 192.168.x.x, 172.etc). But anyway, I don't know if using a non-private address space affect this scenario.

**Comment by StephanNel** [comment] 2020-11-25 20:29
@akshaysngupta

Just deployed 1.18.10 with windows nodes and experiencing the exact same problem. We are using a private cluster and Linux Pods are able to startup and have Healthy Probes. The Windows Pods do start up but the backend health fail with the same timeout error reported in this thread.
