### ISSUE TITLE
Pod ip's not updated in app-gateway

### ISSUE THREAD

**Issue by vishnujanardhanan** [Azure/application-gateway-kubernetes-ingress#442] opened 2019-07-31 11:04 UTC
**Describe the bug**
Pod IP's are not updated in app gateway if it is deleted via kubectl delete pod

**To Reproduce**
Deploy the app
App-gateway ingress controller will add the ip's to backend pool
Delete the pods - kubectl delete pods
IP's are not updated in app-gateway

**Comment by PatricioDanos** [comment] 2019-07-31 14:54
Have you checked the logs of the pod running the ingress controller right after deleting the pod ?

> kubectl logs $(kubectl get pods --show-labels | grep app=ingress-azure | awk '{print $1}') --tail 50

**Comment by vishnujanardhanan** [comment] 2019-08-01 05:32
@PatricioDanos I deleted the pods now and it seems to update the ip's the app-gateway UI in few mins. Though the logs of ingress-controller denotes the operation completed in 20 secs.

But i certainly had the issue yesterday where even after 30 mins the ip's in app-gateway seemed to be old and the health probes were failing. Hence we redeployed the ingress controller and this issue was raised.

I'll give it few days and do a similar test and come back to you. Thanks.

**Comment by delqn** [comment] 2019-08-15 18:45
@vishnujanardhanan I'm closing this issue since we have not heard from you - assuming you no longer have this problem.  But I'd love to learn more about the issue you ran into.  Could you provide sanitized logs or other hints on how to reproduce this?

**Closed by delqn** 2019-08-15 18:45 UTC

**Comment by vishnujanardhanan** [comment] 2019-08-16 02:22
@delqn I haven't seen this issue yet. I'll reopen the case with sufficient logs and steps when I see a re-occurrence.
