### ISSUE TITLE
Multi site listener through AGIC cause the APP Gateway Portal error.

### ISSUE THREAD

**Issue by qinshuang1998** [Azure/application-gateway-kubernetes-ingress#1042] opened 2020-10-29 06:39 UTC
### Although it seems to work properly, I think this is a BUG.

[![BGw4mQ.md.png](https://s1.ax1x.com/2020/10/29/BGw4mQ.md.png)](https://imgchr.com/i/BGw4mQ)

[![BGwJF1.md.png](https://s1.ax1x.com/2020/10/29/BGwJF1.md.png)](https://imgchr.com/i/BGwJF1)

**Comment by mortenlerudjordet** [comment] 2020-10-31 07:09
If you look at the docs it states that the portal does not support viewing the new multi site, so it will display as basic.
Use either PS or Az-cli to get the correct multi site info.

They will hopefully fix the portal at some point.

**Comment by Vishal2696** [comment] 2020-11-03 06:19
This is a duplicate of the issue #962 . This shall be closed.

**Comment by MarcelT-NL** [comment] 2020-11-23 12:19
> If you look at the docs it states that the portal does not support viewing the new multi site, so it will display as basic.
> Use either PS or Az-cli to get the correct multi site info.
> 
> They will hopefully fix the portal at some point.

Listing the setup with PS works, but there is no way to associate rewrite rules etc., because of the multi site setup. Just gives an error and dies. Any ideas? I need this to work around the issue of AGIC dropping the rewrite rules on every update.

**Comment by mortenlerudjordet** [comment] 2020-11-23 13:21
You need to do everything through the aks deployment or else it will just overwrite the stuff you add outside.
This is just how they made it.

These are the only AppGw functions they support at the moment:
https://azure.github.io/application-gateway-kubernetes-ingress/annotations/

Dont think rewrite is one of them, so they will need to implement support for it

**Comment by MarcelT-NL** [comment] 2020-11-23 13:24
> Dont think rewrite is one of them, so they will need to implement support for it
I was afraid of this. This makes it impossible to use the rewrite rules with AGIC. 
The value of the App Gw is getting smaller with each of these issues...

**Comment by MarcelT-NL** [comment] 2020-11-23 13:32
I will submit a feature request

**Comment by Vishal2696** [comment] 2020-11-23 13:51
> You need to do everything through the aks deployment or else it will just overwrite the stuff you add outside.
> This is just how they made it.
> 
> These are the only AppGw functions they support at the moment:
> https://azure.github.io/application-gateway-kubernetes-ingress/annotations/
> 
> Dont think rewrite is one of them, so they will need to implement support for it

No. Not exactly. AGIC can accomodate changes made externally too. Checkout the feature called  AzureIngressProhibitedTarget.
https://github.com/Azure/application-gateway-kubernetes-ingress/tree/master/crds

**Comment by MarcelT-NL** [comment] 2020-11-23 13:52
I submitted a feature request: https://github.com/Azure/application-gateway-kubernetes-ingress/issues/1066

**Comment by MarcelT-NL** [comment] 2020-11-23 13:57
> No. Not exactly. AGIC can accomodate changes made externally too. Checkout the feature called AzureIngressProhibitedTarget.
> https://github.com/Azure/application-gateway-kubernetes-ingress/tree/master/crds

How does this work exactly? 

I you specify TLS in the yaml, AGIC will create the HTTPS listener for you. 
Should I set AzureIngressProhibitedTarget, and after creation manually link the rewrite sets to the listener?
Will AzureIngressProhibitedTarget be applied to both the HTTP and HTTPS listeners?

What happens if the ACME certificate is updated? Will that still work?

Thanks for your support!

**Comment by akshaysngupta** [comment] 2020-12-01 03:46
Closing this as duplicate for https://github.com/Azure/application-gateway-kubernetes-ingress/issues/962

**Closed by akshaysngupta** 2020-12-01 03:46 UTC
